server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    springbootjms:
      com:
        epam:
          activemq:
            jms:
              impl: INFO


simple-example:
  queue: simple-queue
  topic: simple-topic







